import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { services } from "../../../db/schema";

const allowed = new Set(["Disponible", "Asignado", "En camino", "Finalizado"]);
const fail = (error: unknown) => Response.json({ error: error instanceof Error ? error.message : "No se pudo completar la operación" }, { status: 500 });
export async function GET(){try{const rows=await getDb().select().from(services).orderBy(desc(services.createdAt),desc(services.id)).limit(100);return Response.json({services:rows.map(s=>({...s,id:s.code,provider:s.providerName}))})}catch(error){return fail(error)}}
export async function POST(request:Request){try{const body=await request.json() as Record<string,unknown>;if(!body.origin||!body.price||!body.type||!body.company)return Response.json({error:"Faltan datos obligatorios"},{status:400});const code=`A24-${Date.now().toString().slice(-6)}`;const [created]=await getDb().insert(services).values({code,type:String(body.type),company:String(body.company),origin:String(body.origin),destination:String(body.destination||"—"),price:Number(body.price),distance:Number(body.distance||0),eta:15}).returning();return Response.json({service:{...created,id:created.code,provider:created.providerName}},{status:201})}catch(error){return fail(error)}}
export async function PATCH(request:Request){try{const body=await request.json() as {id?:string;status?:string;provider?:string};if(!body.id||!body.status||!allowed.has(body.status))return Response.json({error:"Actualización inválida"},{status:400});const [updated]=await getDb().update(services).set({status:body.status as "Disponible"|"Asignado"|"En camino"|"Finalizado",providerName:body.provider||null,updatedAt:new Date().toISOString()}).where(eq(services.code,body.id)).returning();if(!updated)return Response.json({error:"Servicio inexistente"},{status:404});return Response.json({service:{...updated,id:updated.code,provider:updated.providerName}})}catch(error){return fail(error)}}
