"use client";

import { useEffect, useMemo, useState } from "react";
import { Bell, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Gauge, Headphones, MapPin, Menu, Navigation, Phone, Plus, Search, ShieldCheck, Truck, Users, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Toaster } from "@/components/ui/sonner";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { toast } from "sonner";

type Status = "Disponible" | "Asignado" | "En camino" | "Finalizado";
type Service = { id:string; type:string; origin:string; destination:string; distance:number; price:number; status:Status; company:string; provider?:string; eta?:number };
type AuthUser = { id:number; phone:string; name:string; role:"admin"|"operator"|"provider" };
const seed: Service[] = [
  {id:"A24-1048",type:"Auxilio mecánico",origin:"Av. Córdoba 3180, CABA",destination:"—",distance:7.4,price:52800,status:"Disponible",company:"La Caja",eta:12},
  {id:"A24-1047",type:"Remolque liviano",origin:"San Martín 840, San Isidro",destination:"Av. Maipú 2200, Vicente López",distance:18.6,price:71900,status:"En camino",company:"San Cristóbal",provider:"Grúas Norte",eta:9},
  {id:"A24-1046",type:"Semipesado",origin:"Ruta 9 km 73, Campana",destination:"Parque Industrial Pilar",distance:49.2,price:142500,status:"Asignado",company:"Generali",provider:"Auxilios MG",eta:28},
  {id:"A24-1045",type:"Cambio de neumático",origin:"Av. Rivadavia 10420, CABA",destination:"—",distance:5.1,price:43989,status:"Finalizado",company:"La Caja",provider:"Móvil 24"},
];
const money = new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});

function Logo(){return <div className="brand"><div className="brand-mark">A<span>24</span></div><div><strong>ASISTIR24</strong><small>RED DE ASISTENCIA</small></div></div>}
function Pill({status}:{status:Status}){return <span className={`status ${status.toLowerCase().replace(" ","-")}`}><i/>{status}</span>}

export default function Home(){
  const [user,setUser]=useState<AuthUser|null>(null),[checking,setChecking]=useState(true);
  const [services,setServices]=useState(seed),[role,setRole]=useState<"central"|"prestador">("central"),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[nav,setNav]=useState(false);
  const [form,setForm]=useState({type:"Auxilio mecánico",company:"La Caja",origin:"",destination:"",price:""});
  const filtered=useMemo(()=>services.filter(s=>`${s.id} ${s.origin} ${s.company}`.toLowerCase().includes(query.toLowerCase())),[services,query]);
  const active=services.filter(s=>s.status!=="Finalizado").length;
  useEffect(()=>{fetch("/api/auth/me").then(async r=>{if(!r.ok)throw new Error();return await r.json() as {user:AuthUser}}).then(({user})=>{setUser(user);setRole(user.role==="provider"?"prestador":"central");return fetch("/api/services")}).then(async r=>{if(!r.ok)throw new Error();return await r.json() as {services:Service[]}}).then(data=>{if(data.services?.length)setServices(data.services)}).catch(()=>{}).finally(()=>setChecking(false))},[]);
  async function create(){if(!form.origin||!form.price)return toast.error("Completá el origen y el valor.");try{const r=await fetch("/api/services",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});if(!r.ok)throw new Error();const {service}=await r.json() as {service:Service};setServices([service,...services]);setOpen(false);setForm({...form,origin:"",destination:"",price:""});toast.success(`${service.id} publicado en la red.`)}catch{toast.error("No se pudo guardar. Intentá nuevamente.")}}
  async function update(id:string,status:Status){const provider=status==="Asignado"?"Tu unidad":services.find(s=>s.id===id)?.provider;try{const r=await fetch("/api/services",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status,provider})});if(!r.ok)throw new Error();setServices(services.map(s=>s.id===id?{...s,status,provider}:s));toast.success(status==="Asignado"?"Servicio aceptado. La central fue notificada.":"Estado actualizado.")}catch{toast.error("No se pudo actualizar el servicio.")}}
  if(checking)return <div className="auth-page"><Logo/><p>Ingresando a la red…</p></div>;
  if(!user)return <LoginScreen onLogin={(u)=>{setUser(u);setRole(u.role==="provider"?"prestador":"central")}}/>;
  const initials=user.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();
  return <main className="app-shell"><Toaster richColors position="top-right"/>
    <header className="topbar"><button className="mobile-menu" onClick={()=>setNav(!nav)} aria-label="Abrir menú"><Menu/></button><Logo/>{user.role!=="provider"&&<div className="role-switch"><button className={role==="central"?"active":""} onClick={()=>setRole("central")}>Central</button><button className={role==="prestador"?"active":""} onClick={()=>setRole("prestador")}>Prestador</button></div>}<div className="header-actions"><button className="icon-button"><Bell/><b>3</b></button><button className="user-chip logout" onClick={async()=>{await fetch("/api/auth/me",{method:"DELETE"});setUser(null)}}><span>{initials}</span><div><strong>{user.name}</strong><small>{user.role==="admin"?"Administrador":user.role==="operator"?"Operador":"Prestador"} · Salir</small></div></button></div></header>
    <aside className={`sidebar ${nav?"open":""}`}><nav><button className="nav-active"><Gauge/>Resumen</button><button><Truck/>Servicios <span>{active}</span></button><button><Users/>Prestadores</button><button><MapPin/>Mapa de unidades</button><button><CircleDollarSign/>Liquidaciones</button><button><ShieldCheck/>Empresas</button></nav><div className="support-card"><Headphones/><strong>Central operativa</strong><p>Soporte disponible las 24 horas.</p><a href="tel:+543487210379"><Phone/>3487 210379</a></div></aside>
    <section className="workspace" onClick={()=>nav&&setNav(false)}>{role==="central"?<Central services={filtered} all={services} query={query} setQuery={setQuery} open={open} setOpen={setOpen} form={form} setForm={setForm} create={create}/>:<Provider services={services} update={update}/>}</section>
  </main>
}

function LoginScreen({onLogin}:{onLogin:(user:AuthUser)=>void}){
  const [phone,setPhone]=useState(""),[code,setCode]=useState(""),[step,setStep]=useState<"phone"|"code">("phone"),[busy,setBusy]=useState(false);
  async function requestCode(){if(phone.replace(/\D/g,"").length<10)return toast.error("Ingresá un número válido.");setBusy(true);try{const r=await fetch("/api/auth/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone})});const data=await r.json() as {error?:string;phone:string};if(!r.ok)throw new Error(data.error);setPhone(data.phone);setStep("code");toast.success("Te enviamos el código por WhatsApp.")}catch(error){toast.error(error instanceof Error?error.message:"No se pudo enviar el código.")}finally{setBusy(false)}}
  async function verify(){if(code.length!==6)return toast.error("Ingresá los 6 números del código.");setBusy(true);try{const r=await fetch("/api/auth/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,code})});const data=await r.json() as {error?:string;user:AuthUser};if(!r.ok)throw new Error(data.error);onLogin(data.user);toast.success("Ingreso confirmado.")}catch(error){toast.error(error instanceof Error?error.message:"Código incorrecto.")}finally{setBusy(false)}}
  return <main className="auth-page"><Toaster richColors position="top-right"/><section className="auth-card"><Logo/><div className="auth-copy"><p className="eyebrow">ACCESO SEGURO</p><h1>{step==="phone"?"Ingresá a Asistir24 Red":"Revisá tu WhatsApp"}</h1><p>{step==="phone"?"Usá el número registrado en la red de prestadores.":`Enviamos un código de 6 números al ${phone}.`}</p></div>{step==="phone"?<div className="auth-form"><Label>Número de teléfono</Label><div className="phone-field"><span>🇦🇷 +54</span><Input inputMode="tel" autoComplete="tel" placeholder="11 2345 6789" value={phone} onChange={e=>setPhone(e.target.value)}/></div><Button onClick={requestCode} disabled={busy}>{busy?"Enviando…":"Recibir código por WhatsApp"}</Button></div>:<div className="auth-form otp-form"><Label>Código de verificación</Label><InputOTP maxLength={6} value={code} onChange={setCode}><InputOTPGroup>{[0,1,2,3,4,5].map(i=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP><Button onClick={verify} disabled={busy}>{busy?"Verificando…":"Ingresar"}</Button><button className="change-phone" onClick={()=>{setStep("phone");setCode("")}}>Cambiar número</button></div>}<small className="auth-note">El código vence a los pocos minutos y solo puede usarse una vez.</small></section><div className="auth-brand-panel"><div><ShieldCheck/><h2>La red de asistencia, conectada.</h2><p>Servicios, prestadores y seguimiento operativo en un mismo lugar.</p></div></div></main>
}

function Central({services,all,query,setQuery,open,setOpen,form,setForm,create}:{services:Service[];all:Service[];query:string;setQuery:(v:string)=>void;open:boolean;setOpen:(v:boolean)=>void;form:any;setForm:(v:any)=>void;create:()=>void}){
  const active=all.filter(s=>s.status!=="Finalizado").length;
  return <><div className="page-heading"><div><p className="eyebrow">CENTRAL DE OPERACIONES</p><h1>Servicios en tiempo real</h1><p>Publicá, asigná y seguí cada asistencia desde un solo lugar.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button className="primary-action"><Plus/>Nuevo servicio</Button>}/><DialogContent className="service-dialog"><DialogHeader><DialogTitle>Publicar nuevo servicio</DialogTitle></DialogHeader><div className="form-grid"><Field label="Tipo"><Select value={form.type} onValueChange={(v)=>setForm({...form,type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Auxilio mecánico">Auxilio mecánico</SelectItem><SelectItem value="Remolque liviano">Remolque liviano</SelectItem><SelectItem value="Semipesado">Semipesado</SelectItem><SelectItem value="Servicio express">Servicio express</SelectItem></SelectContent></Select></Field><Field label="Compañía"><Select value={form.company} onValueChange={(v)=>setForm({...form,company:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["La Caja","San Cristóbal","Generali"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Origen" full><Input placeholder="Dirección o coordenadas" value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}/></Field><Field label="Destino (opcional)" full><Input placeholder="Dirección o coordenadas" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/></Field><Field label="Valor ofrecido" full><Input inputMode="numeric" placeholder="$ 0" value={form.price} onChange={e=>setForm({...form,price:e.target.value.replace(/\D/g,"")})}/></Field></div><Button className="publish" onClick={create}>Publicar en la red <ChevronRight/></Button></DialogContent></Dialog></div>
    <div className="metrics"><Metric icon={<Truck/>} tone="orange" label="Servicios activos" value={active} note="+12% esta semana"/><Metric icon={<Navigation/>} tone="blue" label="Unidades en camino" value={all.filter(s=>s.status==="En camino").length} note="ETA promedio 14 min"/><Metric icon={<CheckCircle2/>} tone="green" label="Finalizados hoy" value={18} note="96% sin demoras"/><Metric icon={<Users/>} tone="violet" label="Prestadores disponibles" value={27} note="En CABA y AMBA"/></div>
    <div className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Actividad reciente</h2><p>Últimos servicios publicados</p></div><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar servicio"/></div></div><div className="service-list">{services.map(s=><ServiceRow key={s.id} service={s}/>)}</div></div><MapPanel/></div></>
}
function Field({label,full,children}:{label:string;full?:boolean;children:React.ReactNode}){return <div className={full?"full":""}><Label>{label}</Label>{children}</div>}
function Metric({icon,tone,label,value,note}:{icon:React.ReactNode;tone:string;label:string;value:number;note:string}){return <div><span className={`metric-icon ${tone}`}>{icon}</span><p>{label}</p><strong>{value}</strong><small>{note}</small></div>}
function ServiceRow({service:s}:{service:Service}){return <article className="service-row"><div className="type-icon">{s.type.includes("mecánico")?<Wrench/>:<Truck/>}</div><div className="service-main"><div className="service-title"><strong>{s.id}</strong><Pill status={s.status}/></div><h3>{s.type}</h3><p><MapPin/>{s.origin}</p>{s.destination!=="—"&&<p><Navigation/>{s.destination}</p>}</div><div className="service-meta"><small>{s.company}</small><strong>{money.format(s.price)}</strong><span>{s.distance?`${s.distance} km`:"Km por calcular"}</span></div><button className="row-action"><ChevronRight/></button></article>}
function MapPanel(){return <aside className="panel map-panel"><div className="panel-head"><div><h2>Cobertura activa</h2><p>CABA y AMBA</p></div><span className="live-dot">EN VIVO</span></div><div className="map-visual"><div className="road r1"/><div className="road r2"/><div className="road r3"/><span className="zone z1">CABA</span><span className="zone z2">Zona Norte</span><span className="zone z3">Zona Oeste</span><i className="unit u1"><Truck/></i><i className="unit u2"><Truck/></i><i className="unit u3"><Truck/></i><i className="incident"><Wrench/></i></div><div className="coverage-foot"><div><span className="legend orange-dot"/>3 servicios activos</div><div><span className="legend navy-dot"/>27 unidades online</div></div></aside>}

function Provider({services,update}:{services:Service[];update:(id:string,s:Status)=>void}){
  const [online,setOnline]=useState(false),[providerId,setProviderId]=useState<number|null>(null),[gps,setGps]=useState("Ubicación pendiente");
  const mine=services.find(s=>s.provider==="Tu unidad"&&s.status!=="Finalizado"),offers=services.filter(s=>s.status==="Disponible");
  async function toggleOnline(){
    if(online){if(providerId)await fetch("/api/providers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:providerId,status:"offline"})});setOnline(false);setGps("Ubicación pausada");return}
    if(!navigator.geolocation)return toast.error("Este dispositivo no permite obtener la ubicación.");
    setGps("Buscando ubicación…");
    navigator.geolocation.getCurrentPosition(async({coords})=>{try{const body=providerId?{id:providerId,status:"available",latitude:coords.latitude,longitude:coords.longitude}:{businessName:"Unidad 24",phone:"3487210379",vehicleType:"Auxilio",latitude:coords.latitude,longitude:coords.longitude};const response=await fetch("/api/providers",{method:providerId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error();const {provider}=await response.json() as {provider:{id:number}};setProviderId(provider.id);setOnline(true);setGps("GPS activo · ubicación enviada");toast.success("Ya estás visible para la central.")}catch{setGps("No se pudo enviar la ubicación");toast.error("No se pudo activar la unidad.")}},()=>{setGps("Permiso de ubicación denegado");toast.error("Permití el acceso a la ubicación para trabajar en línea.")},{enableHighAccuracy:true,timeout:12000});
  }
  return <><div className="page-heading provider-heading"><div><p className="eyebrow">APP DEL PRESTADOR</p><h1>Hola, Unidad 24</h1><p>{gps}</p></div><button className={`online ${online?"active":""}`} onClick={toggleOnline}><i/>{online?"EN LÍNEA":"CONECTARME"}</button></div>{mine&&<section className="current-job"><div className="current-top"><span>SERVICIO ACTUAL</span><Pill status={mine.status}/></div><h2>{mine.type} · {mine.id}</h2><div className="route-line"><p><MapPin/><span><small>ORIGEN</small>{mine.origin}</span></p>{mine.destination!=="—"&&<p><Navigation/><span><small>DESTINO</small>{mine.destination}</span></p>}</div><div className="job-actions"><a href={`https://maps.google.com/?q=${encodeURIComponent(mine.origin)}`} target="_blank"><Navigation/>Abrir navegación</a><Button onClick={()=>update(mine.id,mine.status==="Asignado"?"En camino":"Finalizado")}>{mine.status==="Asignado"?"Estoy en camino":"Finalizar servicio"}</Button></div></section>}<div className="provider-stats"><Stat icon={<Clock3/>} label="Estado de unidad" value={online?"Disponible":"Fuera de línea"}/><Stat icon={<CircleDollarSign/>} label="Ganado hoy" value={money.format(124700)}/><Stat icon={<Truck/>} label="Servicios realizados" value="3"/></div><div className="panel offers"><div className="panel-head"><div><h2>Servicios disponibles cerca</h2><p>{online?`${offers.length} oportunidades en tu zona`:"Conectate para recibir oportunidades"}</p></div>{online&&<span className="live-dot">ACTUALIZANDO</span>}</div><div className="offer-grid">{offers.map(s=><article className="offer" key={s.id}><div className="offer-head"><span className="type-icon"><Wrench/></span><div><small>{s.id}</small><h3>{s.type}</h3></div><strong>{money.format(s.price)}</strong></div><div className="offer-route"><p><MapPin/>{s.origin}</p>{s.destination!=="—"&&<p><Navigation/>{s.destination}</p>}</div><div className="offer-info"><span><b>{s.eta} min</b>hasta el origen</span><span><b>{s.distance||"—"} km</b>de recorrido</span></div><Button disabled={!online} onClick={()=>update(s.id,"Asignado")}>Aceptar servicio <ChevronRight/></Button></article>)}</div></div></>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div>{icon}<span><small>{label}</small><strong>{value}</strong></span></div>}
